### ISSUE TITLE
PyCharm Instructions

### ISSUE THREAD

**Issue by ethanejohnsons** [thecesrom/Ignition#41]
Would you mind if I submitted some instructions on how to install this in PyCharm? I struggled somewhat before I was able to figure it out myself :)

**Comment by thecesrom** [comment]
Sure! Please do.

All contributions are welcome.

**Comment by thecesrom** [comment]
I've been thinking about adding a wiki or a `docs` folder if/when the [README](../blob/HEAD/README.md) gets too big

**Comment by thecesrom** [comment]
Closed via #42
